version: "3"
services:
  nodejs:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: bash /usr/script/api.start.sh
    working_dir: /usr/app
    environment:
      MIGRATE_dbConnectionUri: mongodb://mongo:27017/dev
      RABBITMQ_HOST: rabbitmq
    ports:
      - "4000:4000"
    volumes:
      - ./src:/usr/app/src
      - ./api.start.sh:/usr/script/api.start.sh
    depends_on:
      - hub
      - neo4j
      - redis
      - rabbitmq
    links:
      - hub
      - neo4j
      - redis
      - rabbitmq

  redis:
    image: redis
    expose:
      - 6379

  neo4j:
    image: neo4j:4.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./src/seeds/data:/var/lib/neo4j/import/seeds
    environment:
      NEO4J_AUTH: neo4j/root
      NEO4J_dbms_logs_debug_level: DEBUG

  rabbitmq:
    image: "rabbitmq:3-management"
    tty: true
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data

  firefox:
    image: selenium/node-firefox:3.14.0-gallium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-gallium
    ports:
      - "4444:4444"

volumes:
  rabbitmq_data:

